### ISSUE TITLE
HTML Minify plugin v1.0.0

### ISSUE THREAD

**Issue by moalsaleh** [FriendsOfShopware/FroshPlatformHtmlMinify#5] opened 2021-05-17 12:22 UTC
Hallo zusammen,

ich habe mit diesem tollen Plugin folgendes Problem:

Das Plugin führt dazu, dass z. B. Produkte aus dem Produktslider vertikal angeordnet werden.

Deshalb hat ich das Plugin jetzt erstmal deaktivieren müssen.

Beste Grüße

Mohammad
![minify2](https://user-images.githubusercontent.com/84281360/118487720-4a17b600-b71b-11eb-88cb-553694fd7a82.PNG)
![minify1](https://user-images.githubusercontent.com/84281360/118487724-4b48e300-b71b-11eb-8810-f35f177449b3.PNG)

**Comment by tinect** [comment] 2021-05-19 06:13
Hey, sorry for the delay. Is this error based onto the live shop? So I could try reproducing it with the pages source.

**Comment by moalsaleh** [comment] 2021-05-19 06:22
Hello and thanks for the answer.

I deactivated the plugin. I will activate it for you, so you can see what it is.

Best regards

**Comment by tinect** [comment] 2021-05-19 07:07
Hey, please deactivate the plugin, your shop is broken :-)
I don't need to see the activated, I just need to extract the html-code.

You have pagespeed-module in your nginx activated. This can cause such errors with additional minifiers.

Please deactivate the HTML-Minify so I can see what the original code looks like.

**Comment by moalsaleh** [comment] 2021-05-19 07:16
Hey,

i now deactivated the plugin.

**Comment by tinect** [comment] 2021-05-19 07:17
Thanks, I got it! There is a semicolon missing in JS to being merged correctly. Will update this plugin to be able to catch it soon.

**Comment by tinect** [comment] 2021-05-19 07:31
Hey @moalsaleh,

could you please try with this change? https://github.com/FriendsOfShopware/FroshPlatformHtmlMinify/commit/708d2eeb508af137d4e5bb6ed77ea80113d75f9b

Thank you.

**Comment by moalsaleh** [comment] 2021-05-19 08:21
> Hey @moalsaleh,
> 
> could you please try with this change? [708d2ee](https://github.com/FriendsOfShopware/FroshPlatformHtmlMinify/commit/708d2eeb508af137d4e5bb6ed77ea80113d75f9b)
> 
> Thank you.

thanks.

I will definitely test it. I'm at work at the moment and will only be able to test it at home.

**Comment by moalsaleh** [comment] 2021-05-19 18:33
> Hey @moalsaleh,
> 
> could you please try with this change? [708d2ee](https://github.com/FriendsOfShopware/FroshPlatformHtmlMinify/commit/708d2eeb508af137d4e5bb6ed77ea80113d75f9b)
> 
> Thank you.

I want to be honest, I didn't get it right.
Maybe I would rather wait for the update

**Comment by tinect** [comment] 2021-05-20 10:18
Hey @moalsaleh,
I don't release an update without knowing it fixes anything :-)

What is the challenge updating your local `ResponseListener.php`?
You can replace your file content with this: https://raw.githubusercontent.com/FriendsOfShopware/FroshPlatformHtmlMinify/708d2eeb508af137d4e5bb6ed77ea80113d75f9b/src/Listener/ResponseListener.php

Then you can see, if it's fixed on your site.

**Comment by moalsaleh** [comment] 2021-05-20 12:17
Hey tinect,

it works! Thank you very much!

**Comment by tinect** [comment] 2021-06-07 10:45
Release is on the way

**Closed by tinect** 2021-06-07 10:45 UTC
Labels: kind/bug
